### ISSUE TITLE
有些频道实际上是失效的

### ISSUE THREAD

**Issue by qwerttvv** [islercn/BeiJing-Unicom-IPTV-List#1]
我本地239.2.1.X和239.3.1.X都能看

通过盒子抓包是239.3.1.X的

#EXTINF:-1,IPTV6＋
http://192.168.11.1:8888/rtp/239.2.1.197:9016
#EXTINF:-1,IPTV3＋
http://192.168.11.1:8888/rtp/239.2.1.198:9004
#EXTINF:-1,IPTV5＋
http://192.168.11.1:8888/rtp/239.2.1.200:9008
#EXTINF:-1,IPTV8＋
http://192.168.11.1:8888/rtp/239.2.1.201:8072
列表里这几个是失效的

**Comment by qwerttvv** [comment]
另外还有个事儿，两个网段好像是不同的局端网段不同，已知海淀大多数获取是239.2.1.X，朝阳这边儿是239.3.1.X

**Comment by islercn** [comment]
我接上联通的盒子，似乎已经没这几个台了，不过获取频道列表的话这几个还一直存在，但确实看不见了。

联通盒子上提示过两天系统会升级，等等看吧，毕竟之前还有过列表更新后光有频道名没ip的时候呢

**Comment by islercn** [comment]
关于组播IP的问题，就比较复杂了，首先按理说用这个地址段就应该是局端控制，不过我曾遇到过很久没接官方盒子，IP段发生变化（.2变.3），接上官方盒子，升级系统后，IP段又恢复回来的情况。

疫情结束后，我会在朋友家去抓.3，但是估计也不能覆盖所有局/人

**Comment by qwerttvv** [comment]
> 我接上联通的盒子，似乎已经没这几个台了，不过获取频道列表的话这几个还一直存在，但确实看不见了。
> 
> 联通盒子上提示过两天系统会升级，等等看吧，毕竟之前还有过列表更新后光有频道名没ip的时候呢

那个朝阳融媒和文化北京就是抓包有，实际失效很久很久了

这次提示升级不知道会不会有CCTV13高清，或者多几个其他的高清，到时候儿看看吧：）

**Comment by islercn** [comment]
> > 我接上联通的盒子，似乎已经没这几个台了，不过获取频道列表的话这几个还一直存在，但确实看不见了。
> > 联通盒子上提示过两天系统会升级，等等看吧，毕竟之前还有过列表更新后光有频道名没ip的时候呢
> 
> 那个朝阳融媒和文化北京就是抓包有，实际失效很久很久了
> 
> 这次提示升级不知道会不会有CCTV13高清，或者多几个其他的高清，到时候儿看看吧：）

很遗憾，频道并没有更新

**Comment by qwerttvv** [comment]
> > > 我接上联通的盒子，似乎已经没这几个台了，不过获取频道列表的话这几个还一直存在，但确实看不见了。
> > > 联通盒子上提示过两天系统会升级，等等看吧，毕竟之前还有过列表更新后光有频道名没ip的时候呢
> > 
> > 
> > 那个朝阳融媒和文化北京就是抓包有，实际失效很久很久了
> > 这次提示升级不知道会不会有CCTV13高清，或者多几个其他的高清，到时候儿看看吧：）
> 
> 很遗憾，频道并没有更新

哈哈，是这么回事儿，我第二天晚上抓完就对比了一下儿，也扫了几遍，还那样儿

我先用央视频的那个cctv13高清看了

**Comment by anonymous216041** [comment]
前提我家是联通宽带，已经改了桥接，华硕路由拨号。我用提供的频道列表改成rtp://这个形式的链接，导入kodi 和vlc 这两个TV版APP里面，可以正常播放，但是有个问题，总是播放一段时间就卡死。在从新点开这个频道就又能播放。 这个卡死的现象时间不固定，没有找到卡死的规律。请问是为啥呢？

**Comment by qwerttvv** [comment]
> 前提我家是联通宽带，已经改了桥接，华硕路由拨号。我用提供的频道列表改成rtp://这个形式的链接，导入kodi 和vlc 这两个TV版APP里面，可以正常播放，但是有个问题，总是播放一段时间就卡死。在从新点开这个频道就又能播放。 这个卡死的现象时间不固定，没有找到卡死的规律。请问是为啥呢？

1、升级路由固件
2、打开Snooping
3、建议转单播使用

**Comment by anonymous216041** [comment]
华硕路由器已经升级到最新的了。
无线的专业设置里面有一个IGMP  Snooping 停用状态改成了启用
建议转单播使用这个在哪里改呢

**Comment by qwerttvv** [comment]
> 华硕路由器已经升级到最新的了。
> 无线的专业设置里面有一个IGMP Snooping 停用状态改成了启用
> 建议转单播使用这个在哪里改呢

1、开了snooping你再看看组播会不会出毛病，要是还有问题，你看看有没有组播快速切换开关和igmp版本选项，改一改试试
2、应该在iptv选项里有个udpxy选项，打开udpxy，设置端口，即可单播直接用本项目的播放列表，ip和端口要改你自己的

**Comment by anonymous216041** [comment]
我刚才的2个操作竟然成功了，目前1小时不断不卡。
内部网络（lan）下有个IPTV选项卡，我把里面的特殊应用程序下面
使用DHCP路由 从停用，改成了RFC3442&Microfoft
启动组播路由（IGMP PRoxy）从停用改成了启用
udp代理（uDPxy）此处没有修改还用的0  （这个地方如果修改端口了****，是不是就可以用http://192.168.*1:****/rtp/239.2.1.197:9016地址去播放了。） 
IGMP default version 原来就是3，我没有做修改。

在问一句。udp代理（uDPxy）这个地方修改了端口，如果我开了内网穿透，是不是就可以用http://域名：****/rtp/239.2.1.197:9016这种形式在外网播放呢

**Comment by anonymous216041** [comment]
想询问下回访功能如何实现，看友人说在连接后面加?playseek=YYYYMMDDhhmmss-YYYYMMDDhhmmss可以实现

**Comment by qwerttvv** [comment]
时移需要自己去盒子抓包找你自己的地址

**Comment by anonymous216041** [comment]
那外网IPTV可以实现吗？我用xteve+plex 基本实现了内网播放。通过依家直播添加自定义播放目录（但是添加组播地址会有点卡，4K的频道无法播放）。

**Comment by islercn** [comment]
> 那外网IPTV可以实现吗？我用xteve+plex 基本实现了内网播放。通过依家直播添加自定义播放目录（但是添加组播地址会有点卡，4K的频道无法播放）。

UDPXY+端口转发即可
