### ISSUE TITLE
冬奥纪实频道似乎是下线了？

### ISSUE THREAD

**Issue by yooygah** [islercn/BeiJing-Unicom-IPTV-List#10]
冬奥纪实各个清晰度的频道都看不了了

**Comment by islercn** [comment]
官方频道列表就是这样，上次添加的几个频道，也是频道有了之后好多天才添加到列表里的。
可以考虑增加一个“排除无效频道”的列表，通过流量去排除频道有风险，比如我本地网络出问题，可能就把列表清空了。。

**Comment by yooygah** [comment]
原来是这样，感谢二位大佬答疑，看网上有人说移动的IPTV也是7月底把纪实频道撤了，本来以为是奥运转播授权的原因，可是现在奥运结束了却连信号都掐了，也不知道为啥
