### ISSUE TITLE
BTV冬奥相关的都看不到了。

### ISSUE THREAD

**Issue by zhouxiaolong920** [islercn/BeiJing-Unicom-IPTV-List#11]
#EXTINF:-1,BTV冬奥纪实高清
http://192.168.2.1:4022/rtp/239.3.1.243:8000
#EXTINF:-1,BTV冬奥纪实4K
http://192.168.2.1:4022/rtp/239.3.1.120:8000
#EXTINF:-1,BTV冬奥纪实4K
http://192.168.2.1:4022/rtp/239.3.1.121:8000

**Comment by laozhoubuluo** [comment]
关联 Issue: #10
IPTV 冬奥纪实频道撤了

**Comment by qwerttvv** [comment]
教育网的源还能看

**Comment by islercn** [comment]
官方列表不更新，我说明里也说了因为系统延迟推送，可能会有看不了的频道，如果我加判断分析频道是否可看，怕因为我本地网络或者认证等各种原因误删，这几天我单独加一个筛选过的列表，观察一段时间看是否稳定

**Comment by laozhoubuluo** [comment]
根据北京广播电视台最新通知，冬奥纪实频道与科教频道重组为纪实科教频道（地面/户户通标清、上星高清、地面8K制式播出）、体育休闲频道（地面标清、高清、4K同播）。
IPTV 看项目主项目是已经重新加回了体育休闲高清频道，不过我这里 udpxy 无法看，盒子不太确定能不能看。
