### ISSUE TITLE
楼主，现在已经开放了cctv13的高清频道，看看能不能更新源，谢谢

### ISSUE THREAD

**Issue by iinlanjian** [islercn/BeiJing-Unicom-IPTV-List#4]

**Comment by islercn** [comment]
我接上联通盒子试了试，也没有13的高清啊，你是哪个片区的？

**Comment by qwerttvv** [comment]
北京联通现在没有CCTV13HD啊，你从下边儿挑一个用吧

http://hdtv.lzu6.edu.cn/hls/jlu_cctv13.m3u8
# http://yuniptvun100.chinayungu.cn:65530/live/cctv13/index.m3u8
# rtmp://ivi6.bupt.edu.cn/livetv/cctv13hd
# http://itv.ahau.edu.cn/hls/cctv13hd.m3u8
# http://hdtv.haust.edu.cn/hls/cctv13hd.m3u8
# http://221.179.136.142/PLTV/88888888/224/3221226316/1.m3u8
# http://221.179.136.143/PLTV/88888888/224/3221226316/1.m3u8
# http://221.179.136.144/PLTV/88888888/224/3221226316/1.m3u8
# http://221.179.136.145/PLTV/88888888/224/3221226316/1.m3u8
# http://111.13.42.42/PLTV/88888888/224/3221226159/1.m3u8
# http://111.13.42.43/PLTV/88888888/224/3221226159/1.m3u8
# http://111.13.42.44/PLTV/88888888/224/3221226159/1.m3u8
# http://111.13.42.45/PLTV/88888888/224/3221226159/1.m3u8
# http://221.179.136.150/PLTV/88888888/224/3221226159/1.m3u8
# http://221.179.136.151/PLTV/88888888/224/3221226159/1.m3u8

**Comment by islercn** [comment]
你可能理解错了，目前这份列表是全自动抓取的，让大家能够及时知晓联通频道的变化，我只是偶尔调整下频道顺序以及修正抓包代码

所以这份列表不是那种手工维护的大全型列表，全自动抓取没法弄得那么智能

过年期间可以考虑弄再修护一份人工整合的吧（我自己是有一份全高清的列表的），但是众口难调，而且每个人网络情况不一样，放出来也不一定满足你的需求
