### ISSUE TITLE
频道变化了

### ISSUE THREAD

**Issue by qwerttvv** [islercn/BeiJing-Unicom-IPTV-List#9]
茶频道
    rtp://239.3.1.97:8001
    CCTV-4 中文国际 欧洲
    rtp://239.3.1.213:4220
    CCTV-4 中文国际 美洲
    rtp://239.3.1.214:4220
    CGTN 新闻
    rtp://239.3.1.215:4220
    CGTN 记录
    rtp://239.3.1.216:4220
    CGTN 西班牙语
    rtp://239.3.1.217:4220
    CGTN 法语
    rtp://239.3.1.218:4220
    CGTN 阿拉伯语
    rtp://239.3.1.219:4220
    CGTN 俄语
    rtp://239.3.1.220:4220

新增了几个台，砍了一个熊猫频道

**Comment by islercn** [comment]
我这里确实能看这几个频道了，但是列表貌似还没更新，等等看吧

**Comment by islercn** [comment]
已经更新了

**Comment by anonymous216041** [comment]
冬奥纪实频道没信号了？

**Comment by qwerttvv** [comment]
> 冬奥纪实频道没信号了？

官方列表里好像7月底就去掉了，但是信号是这几天才掐了
